import { NextResponse } from "next/server";
import OpenAI from "openai";
export const runtime="nodejs";
export const maxDuration=300;

function cfg(){const base=String(process.env.NEXTCLOUD_URL||"").replace(/\/+$/,"");const user=String(process.env.NEXTCLOUD_USERNAME||"");const pass=String(process.env.NEXTCLOUD_APP_PASSWORD||"");const root=String(process.env.NEXTCLOUD_LRC_PATH||"/LRC-Agent");if(!base||!user||!pass)throw new Error("Nextcloud config missing");return{base,user,pass,root};}
function auth(u:string,p:string){return `Basic ${Buffer.from(`${u}:${p}`).toString("base64")}`}
function url(c:ReturnType<typeof cfg>,rel:string){const p=[...c.root.split("/").filter(Boolean),...rel.split("/").filter(Boolean)].map(encodeURIComponent).join("/");return `${c.base}/remote.php/dav/files/${encodeURIComponent(c.user)}/${p}`;}
async function dl(c:ReturnType<typeof cfg>,rel:string){const r=await fetch(url(c,rel),{headers:{Authorization:auth(c.user,c.pass)},cache:"no-store"});if(!r.ok)throw new Error(`GET ${r.status}`);return Buffer.from(await r.arrayBuffer());}
function splitWav(buf:Buffer,max=18*1024*1024){let pos=12,fmt=-1,data=-1,size=0;while(pos+8<=buf.length){const id=buf.toString("ascii",pos,pos+4),n=buf.readUInt32LE(pos+4),body=pos+8;if(id==="fmt ")fmt=body;if(id==="data"){data=body;size=Math.min(n,buf.length-body);break}pos=body+n+(n%2)}if(fmt<0||data<0)throw new Error("Invalid WAV");const format=buf.readUInt16LE(fmt),ch=buf.readUInt16LE(fmt+2),sr=buf.readUInt32LE(fmt+4),br=buf.readUInt32LE(fmt+8),ba=buf.readUInt16LE(fmt+12),bits=buf.readUInt16LE(fmt+14);if(format!==1)throw new Error(`WAV format ${format}`);const n=Math.floor(max/ba)*ba,out:{b:Buffer;off:number}[]=[];for(let s=0;s<size;s+=n){const len=Math.min(n,size-s),h=Buffer.alloc(44);h.write("RIFF",0);h.writeUInt32LE(36+len,4);h.write("WAVE",8);h.write("fmt ",12);h.writeUInt32LE(16,16);h.writeUInt16LE(format,20);h.writeUInt16LE(ch,22);h.writeUInt32LE(sr,24);h.writeUInt32LE(br,28);h.writeUInt16LE(ba,32);h.writeUInt16LE(bits,34);h.write("data",36);h.writeUInt32LE(len,40);out.push({b:Buffer.concat([h,buf.subarray(data+s,data+s+len)]),off:s/br})}return out;}

export async function GET(req:Request){try{const u=new URL(req.url);const name=u.searchParams.get("audio")||"Atemschuld - gekürzt.wav";const c=cfg(),buf=await dl(c,`done/${name}`),parts=splitWav(buf);const openai=new OpenAI({apiKey:String(process.env.OPENAI_API_KEY||"")});const words:any[]=[];const texts:string[]=[];for(let i=0;i<parts.length;i++){const p=parts[i];const file=new File([new Uint8Array(p.b)],`chunk-${i+1}.wav`,{type:"audio/wav"});const tr:any=await openai.audio.transcriptions.create({file,model:"whisper-1",response_format:"verbose_json",timestamp_granularities:["word","segment"],language:"de",prompt:"Deutschsprachiger experimenteller Gesang. Bitte Wörter möglichst wörtlich erfassen, insbesondere: Ungerechtigkeit brennt, Unrecht lodert, Flutländer, Dürreländer, Brandländer, Kolonialismus, Klimakollaps, Verantwortungslosigkeit, Atemschuld, Blutschuld, Bruchschuld."} as any);texts.push(String(tr.text||""));for(const w of tr.words||[])words.push({word:String(w.word),start:Number(w.start)+p.off,end:Number(w.end)+p.off});}return NextResponse.json({ok:true,chunks:parts.length,text:texts.join(" "),words});}catch(e:any){return NextResponse.json({ok:false,error:e?.message||String(e)},{status:500});}}
